tests/algorithm_test.js, tests/pipeline_tests.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/system-test-node/59)
=> fix algorithm hot workers

tests/algorithm_test.js
will revision when logs from task-executor will be available
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/system-test-node/60)
=> Added timeout according to elastic logs

config/config.js, package-lock.json, package.json, tests/algorithm_test.js, utils/etcd/etcd.js
Added etcd reading upon failed selector test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/system-test-node/61)
=> Node selector debug etcd

tests/algorithm_test.js
Some resource optimization, cleaned the db and increased cpu in aws.
kube-HPC/hkube#1660
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/system-test-node/75)
=> Algorithmtest stabilization

tests/pipeline_tests.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/system-test-node/79)
=> pipeline active TTL expired fix

additionalFiles/defaults/algorithms/alg1.js, additionalFiles/defaults/algorithms/algorithmList.js, package-lock.json, tests/algorithm_test.js, tests/pipeline_tests.js, utils/algorithmUtils.js, utils/pipelineUtils.js, utils/webhookServer/package-lock.json, utils/webhookServer/package.json
Updated code for the utils, new tests for bulk store of algo & pipelines
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/system-test-node/86)
=> Insert bulk pipeline test

tests/cliTests.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/system-test-node/89)
=> hkubectl data migration (export) tests

tests/pipeline_tests.js, utils/pipelineUtils.js
Added e2e test for pipeline insert
kube-HPC/hkube#1882
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/system-test-node/95)
=> pipeline overwrite test

tests/cliTests.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/system-test-node/96)
=> pipeline cli exsisting pipeline test

additionalFiles/defaults/algorithms/stayup.js, config/index.js, pipelines/statelessPipe.js, tests/algorithm_test.js, utils/algorithmUtils.js
kube-HPC/hkube#1860
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/system-test-node/101)
=> Pods and jobs e2e tests

tests/algorithm_test.js, utils/graphql/queries/all-algorithms.js, utils/socketGet.js
Added two tests to check the newly added feature in the following issue: kube-HPC/hkube#1811
=> Testing feature - 'not satisfied' workers

tests/algorithm_test.js
Fixing 2 problematic tests in algorithm tests, which failed since we are not supporting Python version 2 anymore.
Now using Python version 3.
=> Fix algorithm-test file

config/index.js, pipelines/pipelineFlowAndList.js, tests/pipeline_tests.js
After the changes made in this PR: https://github.com/kube-HPC/parsers.hkube/pull/31
which fixed the bugs explained there, a new test case for pipeline was added.
Another test was fixed
=> pipeline additional test

tests/algorithm_test.js, utils/algorithmUtils.js, utils/kubeCtl.js
=> e2e for workerCustomResources, some algorithmUtils.

package-lock.json, test/tests/longTests/long running .js, tests/High_Availability.js, tests/algorithmBuild.js, tests/algorithm_test.js, tests/cliTests.js, tests/codeApi.js, tests/datasource_tests.js, tests/jagearTest.js, tests/node_tests.js, tests/pipeline_tests.js, tests/processEvent.js, tests/streaming_tests.js, tests/swaggerCalls.js, utils/algorithmUtils.js, utils/createPipeline.js, utils/datasourceUtils.js, utils/elasticsearch.js, utils/generateRandomJson.js, utils/jaeger.js, utils/kubeCtl.js, utils/logger.js, utils/pipelineUtils.js, utils/preferredUtils.js, utils/socketGet.js, utils/webhook.js
In this PR:
* Some tests have been modified, to be independent.
* Some tests have changed so now they won't fail when reaching undefined, when it's not related to the purpose of the test.
* Garbage collection - algorithms and pipelines are now collected, and deleted after tests finish running.
* Organised some files for better readability.
No related issue.
=> Tests fixes

.github/workflows/main.yml, config/config.js, tests/High_Availability.js, tests/algorithm_test.js, tests/codeApi.js, tests/jagearTest.js, tests/node_tests.js, tests/pipeline_tests.js, tests/swaggerCalls.js, travis/values-pub-template.yml, utils/algorithmUtils.js, utils/gc.js, utils/jaeger.js, utils/pipelineUtils.js, utils/results.js
=> Rest authentication and authorization

additionalFiles/alg.yaml, additionalFiles/depsInstallCmd/alg1.yaml, additionalFiles/importAlgorithms/6o5yjjiy.json, additionalFiles/importAllData/algorithms/6o5yjjiy.json, pipelines/ttlPipe.js, tests/algorithmBuild.js, tests/algorithm_test.js, tests/codeApi.js, tests/pipeline_tests.js, tests/streaming_tests.js, utils/algorithmUtils.js, utils/results.js
Some system tests were handled to make sure they pass.
Added some logging to find out why a test fails. Much more logs are needed, but it's a start.
=> Problematic tests and logging

tests/algorithm_test.js, tests/cliTests.js, utils/algorithmUtils.js
a bit more fixes after last nightly tests.
also, fixed new post and put for algorithms store after implementation changed here:
https://github.com/kube-HPC/hkube/pull/2110
=> More test fixes

.github/workflows/main.yml, package-lock.json, package.json, test/tests/HAtests/failPipelineDriver.js, test/tests/algorithm_retry.js, test/tests/longTests/pipelineDriver_failover.js, tests/High_Availability.js, tests/algorithm_test.js, tests/codeApi.js, tests/graphql_tests.js, tests/jagearTest.js, tests/pipeline_tests.js, tests/swaggerCalls.js, utils/pipelineUtils.js, utils/results.js, utils/socketGet.js
Added test authentication via GraphQL for this issue:
https://github.com/kube-HPC/hkube/issues/2082
This PR: https://github.com/kube-HPC/hkube/pull/2100
And the current PR, should be merged together.
=> Test modify for graphql with keycloak

tests/algorithm_test.js, utils/algorithmUtils.js
Added tests for new algorithms volumes implementation.
Related issue - https://github.com/kube-HPC/hkube/issues/2104
=> Volume tests

tests/algorithm_test.js, tests/cliTests.js, tests/streaming_tests.js, utils/misc_utils.js
improved garbage collection in CLI tests.
=> Garbage collection

package-lock.json, package.json, tests/pipeline_tests.js, utils/graphql/queries/job-by-id-query.js
https://github.com/kube-HPC/hkube/issues/2112
=> job invoker e2e

tests/algorithm_test.js, tests/pipeline_tests.js, utils/pipelineUtils.js
=> algorithm and pipeline tests for auditTrail

tests/High_Availability.js, tests/algorithm_test.js, tests/cliTests.js, tests/codeApi.js, tests/jagearTest.js, tests/node_tests.js, tests/pipeline_tests.js, tests/streaming_tests.js, tests/swaggerCalls.js
https://github.com/kube-HPC/hkube/issues/2077
=> cli test changes

tests/swaggerCalls.js
=> execute E2E tests
